// ── Scan History utilities ─────────────────────────────────────────────────────
export const HISTORY_KEY = 'cs_scan_history_v1'
export const HISTORY_CAP = 100

export const TF_COLORS = {
  '1m':'#ff6b6b','3m':'#ffa94d','5m':'#ffd43b','15m':'#69db7c',
  '30m':'#38d9a9','1h':'#4dabf7','4h':'#9775fa','1d':'#f783ac',
}

export function historyLoad() {
  try { return JSON.parse(localStorage.getItem(HISTORY_KEY) || '{}') } catch { return {} }
}
export function historySave(data) {
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(data))
    // Dispatch storage event so same-tab listeners (HistorySection) can react
    window.dispatchEvent(new StorageEvent('storage', { key: HISTORY_KEY }))
  } catch {}
}

export function historyAddAlerts(alerts) {
  if (!alerts || !alerts.length) return
  const data = historyLoad()
  for (const a of alerts) {
    const tf = a.timeframe || 'unknown'
    if (!data[tf]) data[tf] = []
    const minute = Math.floor(a.time / 60000)
    if (data[tf].some(h => h.symbol === a.symbol && h.scannerId === a.scannerId && Math.floor(h.time/60000) === minute)) continue
    data[tf].unshift({
      id: a.id, symbol: a.symbol, timeframe: tf,
      time: a.time, side: a.side,
      scannerName: a.scannerName, scannerIcon: a.scannerIcon || '',
      close:   a.details?.highestClose ?? a.details?.close ?? null,
      entry:   a.details?.lowestOpen   ?? a.details?.entry ?? null,
      gainPct: a.details?.gainPct      ?? null,
      rsi14:   a.details?.rsi14        ?? null,
      ema9:    a.details?.ema9         ?? null,
      ema20:   a.details?.ema20        ?? null,
      adx:     a.details?.adx          ?? null,
      volume:  a.volume                ?? 0,
      scannerId: a.scannerId,
    })
    if (data[tf].length > HISTORY_CAP) data[tf] = data[tf].slice(0, HISTORY_CAP)
  }
  historySave(data)
}

export function fmtHistoryDate(ts) {
  const d = new Date(ts)
  return d.toLocaleDateString('en-GB', { day:'2-digit', month:'short', year:'numeric' }) +
    ' ' + d.toLocaleTimeString('en-GB', { hour:'2-digit', minute:'2-digit', second:'2-digit' })
}

export function tvUrl(symbol, tf = '15m') {
  const m = {'1m':'1','3m':'3','5m':'5','15m':'15','30m':'30','1h':'60','4h':'240','1d':'D','Day':'D'}
  return `https://www.tradingview.com/chart/?symbol=BYBIT:${symbol.replace('USDT','')}USDT.P&interval=${m[tf]||'15'}`
}

export function exportHistoryCSV(historyData, tfFilter) {
  const tfsToExport = tfFilter === 'all' ? Object.keys(historyData) : [tfFilter]
  const allRows = []

  // ── Report header (text-only, no icons) ──
  const COL_COUNT = 15
  const center = (text) => {
    const pad = Math.max(0, Math.floor((COL_COUNT - 1) / 2))
    const row = new Array(COL_COUNT).fill('')
    row[pad] = text
    return row
  }

  allRows.push(center('COINS SNIPER - SCAN HISTORY REPORT'))
  allRows.push(center('DELTA EXCHANGE INDIA - PATTERN SCAN LOG'))
  allRows.push(center(`Exported: ${fmtHistoryDate(Date.now())}`))
  allRows.push(center(`Filter: ${tfFilter === 'all' ? 'All Timeframes' : tfFilter.toUpperCase()}`))
  allRows.push(new Array(COL_COUNT).fill(''))  // blank row

  const HEADERS = [
    'No.', 'Date', 'Time', 'Symbol', 'Timeframe',
    'Direction', 'Pattern Name', 'Entry Price', 'Close Price',
    'Gain %', 'RSI-14', 'EMA-9', 'EMA-20', 'ADX', '24H Volume (USDT)'
  ]

  for (const tf of tfsToExport) {
    const items = historyData[tf] || []
    if (!items.length) continue

    // Section heading
    allRows.push(center(`--- TIMEFRAME: ${tf.toUpperCase()} (${items.length} records) ---`))
    allRows.push(HEADERS)

    items.forEach((h, i) => {
      const d     = new Date(h.time)
      const date  = d.toLocaleDateString('en-GB', { day:'2-digit', month:'short', year:'numeric' })
      const time  = d.toLocaleTimeString('en-GB', { hour:'2-digit', minute:'2-digit', second:'2-digit' })
      const fmtN  = (v, dp = 4) => v != null ? parseFloat(v).toFixed(dp) : ''
      allRows.push([
        i + 1,
        date,
        time,
        h.symbol,
        (h.timeframe || '').toUpperCase(),
        h.side === 'bull' ? 'BULL' : 'BEAR',
        h.scannerName || '',
        fmtN(h.entry),
        fmtN(h.close),
        h.gainPct != null ? parseFloat(h.gainPct).toFixed(2) + '%' : '',
        h.rsi14   != null ? parseFloat(h.rsi14).toFixed(1)  : '',
        fmtN(h.ema9),
        fmtN(h.ema20),
        h.adx     != null ? parseFloat(h.adx).toFixed(1)    : '',
        h.volume  >  0    ? h.volume                        : '',
      ])
    })

    allRows.push(new Array(COL_COUNT).fill(''))  // blank row after each TF
  }

  // Footer
  allRows.push(center(`Total records: ${tfsToExport.reduce((s,tf) => s+(historyData[tf]||[]).length, 0)}`))
  allRows.push(center('Generated by Coins Sniper - coin-sniper.vercel.app'))

  // Build CSV
  const csv = allRows.map(row =>
    row.map(cell => {
      const s = String(cell ?? '')
      return s.includes(',') || s.includes('"') || s.includes('\n')
        ? `"${s.replace(/"/g, '""')}"` : s
    }).join(',')
  ).join('\n')

  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `CoinSniper_History_${tfFilter}_${new Date().toISOString().slice(0,10)}.csv`
  a.click()
  URL.revokeObjectURL(url)
}
